name: Crown Framework
author: MaliciousHD
description: Crown Framework - Built for Serious British Roleplay

tasks:
  - action: download_github
    src: https://github.com/overextended/oxmysql
    ref: main
    dest: ./resources/[standalone]/oxmysql

  - action: download_github
    src: https://github.com/JurassicWaste/UKRP1
    ref: main
    dest: ./tmp/crown_framework

  - action: move_path
    src: ./tmp/crown_framework/resources/[crown]
    dest: ./resources/[crown]

  - action: copy_path
    src: ./tmp/crown_framework/server.cfg
    dest: ./server.cfg

  - action: connect_database

  - action: query_database
    file: ./tmp/crown_framework/sql/crown_framework.sql